"""Write a generated sealed product catalog into the set files, from the TCGCSV catalog and the PPT sealed cache.

Usage:
  python3 tools/ppt/sealed_catalog.py            dry run: report the parse rates and sample rows
  python3 tools/ppt/sealed_catalog.py --write    write '### Product catalog' in each set file, and
                                                  docs/sets/sealed-multi-set.md for the other groups

For each physical sealed product (TCGCSV products with no card number; code cards are left out):
- Kind: from whole words in the product name.
- Packs: from the TCGplayer description, then the product name, then a default for the kind.
  The 'Packs from' column names the source. Other products get 'Unknown'.
- Holds: for a case or a display, what it holds (from the description or the name).
- Release: the TCGCSV release date, else the set's release date from its era file or set file (quarter).
- PPT price: yes when the PPT sealed cache has the product.
Prices change daily, so they stay in tools/ppt/cache/. The docs hold only facts that do not change.
"""
import collections, glob, json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..", "..")
DOCS = os.path.join(ROOT, "docs", "sets")
TCGCSV = os.path.join(ROOT, "tools", "cardlist", "cache", "tcgcsv")
SEALED = os.path.join(HERE, "cache", "sealed")
GROUP_MAP = json.load(open(os.path.join(ROOT, "tools", "cardlist", "tcgcsv-map.json")))
SLUG_OF = {g: s for s, gs in GROUP_MAP.items() for g in gs}
MARK_START = "<!-- product-catalog:start (generated by tools/ppt/sealed_catalog.py; do not edit) -->"
MARK_END = "<!-- product-catalog:end -->"

WORDS = {w: i for i, w in enumerate("zero one two three four five six seven eight nine ten eleven twelve".split())}
WORDS.update({"eighteen": 18, "twenty": 20, "twenty-four": 24, "thirty-six": 36, "thirty six": 36, "forty": 40})
NUM = r"(\d+|" + "|".join(sorted(map(re.escape, WORDS), key=len, reverse=True)) + r")"
# The words between the count and "packs" must not hold a sentence end or a nearer count, so "45 cards. Each box
# also contained eight XY booster packs" gives 8. Three-digit numbers stay allowed for the set name "151".
GAP_WORD = r"(?!(?:\d{1,2}|" + "|".join(sorted(map(re.escape, WORDS), key=len, reverse=True)) + r")(?![\w-]))[\w&:'’—–-][\w&.:'’—–-]*(?<!\.)\s+"
PACKS_RE = re.compile(r"(?<![\w—–-])(?!151\b)" + NUM + r"\s+(?:\(\d+\)\s+)?(?:" + GAP_WORD + r"){0,8}?(?:booster|mini)\s+packs?\b", re.I)
HOLDS_RE = re.compile(NUM + r"\s+(?:[\w&.:'’—–-]+\s+){0,6}?(booster boxes|elite trainer boxes|booster bundles|build & battle boxes|"
                      r"collections|tins|blisters|trainer kits|theme decks|mini tins)\b", re.I)
KINDS = [
    ("Prize pack", r"\bprize pack series\b"),
    ("Case or display", r"\b(case|display)\b"),
    ("Booster box", r"\bbooster box\b"),
    ("Elite Trainer Box", r"\belite trainer box\b"),
    ("Deck", r"\b(theme deck|starter deck|battle deck|trainer kit|training kit|league battle|world championship|deck bundle)\b"),
    ("Booster pack", r"\bmini booster pack\b|\bbooster pack$|\bseries \d+ pack$"),
    ("Booster bundle", r"\bbooster bundle\b"),
    ("Build & Battle", r"\bbuild (?:&|and) battle\b"),
    ("Blister", r"\bblisters?\b|\bcheck ?lane\b"),
    ("Tin", r"\btins?\b"),
    ("Booster pack", r"\b(booster pack|sleeved booster|fun pack|mini booster)\b"),
    ("Collection", r"\b(collection|premium|box|chest|binder|album|figure|poster|pin)\b"),
]
DEFAULT_PACKS = {"Booster box": 36, "Booster bundle": 6, "Build & Battle": 4, "Booster pack": 1, "Prize pack": 1}
# A deck product has fixed cards. The catalog leaves it out when it holds no booster pack (no random pull).
DECK_PRODUCT = re.compile(r"(?i)\b(theme decks?|starter decks?|battle decks?|battle arena|trainer kits?|training kits?|"
                          r"league battle|world championship|starter set|battle academy|ex battle stadium|master trainer|"
                          r"my first battle|trainer battle deck|deck)\b")


def is_deck_product(name):
    if re.search(r"(?i)\bbuild (?:&|and) battle\b|\bdeck box(?:es)?\b", name):
        return False
    return bool(DECK_PRODUCT.search(name))
BULBAPEDIA = os.path.join(HERE, "cache", "bulbapedia")
BP_PAGES = {"wizards-of-the-coast": ["Original", "Neo"], "e-card": ["Legendary Collection", "E-Card"], "ex": ["EX"],
            "diamond-pearl-platinum": ["Diamond & Pearl", "Platinum"],
            "heartgold-soulsilver": ["HeartGold & SoulSilver", "Call of Legends"], "black-white": ["Black & White"],
            "xy": ["XY"], "sun-moon": ["Sun & Moon"], "sword-shield": ["Sword & Shield"],
            "scarlet-violet": ["Scarlet & Violet"], "mega-evolution": ["Mega Evolution"]}
BP_STOP = {"pokemon", "tcg", "the", "and", "of", "series", "xy", "sm", "sun", "moon", "sword", "shield", "scarlet",
           "violet", "mega", "evolution", "black", "white", "ex", "gx", "v"}
BP_KEY = ("tin", "box", "collection", "deck", "blister", "elite", "trainer", "kit", "pack", "bundle", "chest", "binder",
          "album", "arena", "stadium")


def bp_clean(s):
    s = re.sub(r"\{\{TCGMerchGallery.*?\n\}\}", " ", s, flags=re.S)
    s = re.sub(r"\{\{(?:TCG|p|TCGMerch)\|(?:[^{}|]*\|)*([^{}|]*)\}\}", r"\1", s)
    s = re.sub(r"\[\[(?:[^\]|]*\|)?([^\]]*)\]\]", r"\1", s)
    s = re.sub(r"\{\{[^{}]*\}\}", " ", s)
    s = re.sub(r"'{2,3}|<[^>]+>", "", s)
    return re.sub(r"\s+", " ", s)


def bp_tokens(name, stop=True):
    # Leave out bracketed text, parenthesized text, and quoted deck names such as "Red Frenzy".
    name = re.sub(r"\[.*?\]|\(.*?\)|\".*?\"|“.*?”", " ", name.lower()).replace("-", " ").replace("é", "e")
    words = {re.sub(r"(es|s)$", "", w) if len(w) > 3 else w for w in re.findall(r"[a-z0-9]+", name)}
    return words - BP_STOP if stop else words


def bp_sections():
    # {page name: [(section title, title tokens, pack count or None, the text names a booster pack)]}
    import subprocess, urllib.parse
    os.makedirs(BULBAPEDIA, exist_ok=True)
    out = {}
    for page in sorted({p for v in BP_PAGES.values() for p in v}):
        title = f"{page} TCG Series merchandise"
        path = os.path.join(BULBAPEDIA, title.replace(" ", "_").replace("&", "_") + ".wiki")
        if not os.path.exists(path) or os.path.getsize(path) < 500:
            subprocess.run(["curl", "-sL", "-m", "60", "-A", "PokeVendor-research/1.0", "-o", path,
                            "https://bulbapedia.bulbagarden.net/w/index.php?title=" + urllib.parse.quote(title) + "&action=raw"])
        parts = re.split(r"^==([^=].*?)==\s*$", open(path, errors="ignore").read(), flags=re.M)
        secs = []
        for i in range(1, len(parts) - 1, 2):
            text = bp_clean(parts[i + 1]).split("Product images:")[0]
            m = PACKS_RE.search(text)
            n = num(m.group(1)) if m else None
            if n is None and re.search(r"\b(?:a|one)\s+(?:[\w&'’.:-]+\s+){0,3}?booster pack\b", text, re.I):
                n = 1
            secs.append((parts[i].strip(), bp_tokens(parts[i]), n, bool(re.search(r"booster pack", text, re.I))))
        out[page] = secs
    return out


GROUP_NAMES = {}


def own_set_tokens(gid):
    # Title tokens of the product's own set, from the TCGCSV group name, such as "XY - Primal Clash" or "SV02: Paldea Evolved".
    if gid not in SLUG_OF:
        return set()
    if not GROUP_NAMES:
        GROUP_NAMES.update({g["groupId"]: g["name"] for g in json.load(open(os.path.join(SEALED, "_groups.json")))})
    return bp_tokens(re.sub(r"^[A-Za-z]+\d*[a-z]?\s*[:-]\s+", "", GROUP_NAMES.get(gid, "")))


def bp_best(name, era, entries, own_set=frozenset(), accept=None):
    # The best Bulbapedia section entry for a product name, or None. entries: {page: [(title, title tokens, ...)]}.
    # A name with no word from its own set also scores with the set's words, and a title with the set's words gets a
    # small bonus, so "Elite Trainer Box [Kyogre]" in Primal Clash matches "Primal Clash Elite Trainer Box", not
    # "XY Elite Trainer Box". A title with every word from the brackets also scores on those words, so
    # "Enhanced 2-Pack Blister Pack [Latios, Zekrom & Palkia]" matches its own blister section.
    nt = bp_tokens(name)
    bases = [nt, nt | own_set] if own_set and not nt & own_set else [nt]
    # Words in brackets, and a year or series number in parentheses, such as "(Fall 2023)" or "(Series 2)".
    bracket = set().union(*(bp_tokens(b) for b in re.findall(r"\[(.*?)\]", name)),
                          *({m.group(1) or m.group(2)} for m in re.finditer(
                              r"\((?:(?:fall|spring|summer|winter)\s+)?((?:19|20)\d\d)\)|\(series\s+(\d+)\)", name, re.I)))
    raw = bp_tokens(name, stop=False)
    # A booster pack must not match a Booster Bundle or Mini Packs section, and a booster box must not match a
    # Build & Battle section. Other kind differences are the same product under another name ("Booster Display Box").
    kind, allowed = kind_of(name), {"Booster pack": {"Booster pack"}, "Booster box": {"Booster box", "Case or display"}}
    best, best_key, tied = None, (0.0, 0.0), False
    for page in BP_PAGES.get(era) or [p for v in BP_PAGES.values() for p in v]:
        for entry in entries.get(page, []):
            tt = entry[1]
            if not tt or not (nt & tt):
                continue
            if kind in allowed and kind_of(entry[0]) not in allowed[kind]:
                continue
            if not any(k in " ".join(nt) and k in " ".join(tt) for k in BP_KEY):
                continue
            score = max(len(base & tt) / len(base | tt) for base in bases)
            if bracket and bracket <= tt:
                # A title with every bracket word also scores on those words. When at least half of the rest of the
                # name matches too, the title wins: "Knock Out Collection [Chien-Pao]" is "... Alakazam & Chien-Pao".
                full = max(len((base | bracket) & tt) / len(base | bracket | tt) for base in bases)
                score = full + 1.0 if score >= 0.5 else full
            if len(bases) > 1 and own_set <= tt:
                score += 0.01
            # With equal scores, more shared words (stop words included) win, so "Black Kyurem Box" beats "Kyurem Box".
            title_raw = bp_tokens(entry[0], stop=False)
            key = (score, len(raw & title_raw) / len(raw | title_raw))
            # accept(entry) is an optional extra test, such as the release year. It runs only for a better key.
            if key > best_key and (accept is None or accept(entry)):
                best, best_key, tied = entry, key, False
            elif best and key == best_key and entry[0] != best[0] and (accept is None or accept(entry)):
                tied = True
    # With no era, two different sections with the same best key are different product lines, such as the
    # "Fall 2018 Collector Chest" and the "Fall 2022 Collector Chest" for a "Fall 2025 Collector Chest".
    if tied and not era:
        return None
    return best if best_key[0] >= 0.6 else None


def bp_packs(name, kind, era, sections, own_set=frozenset()):
    # (packs, source) from the best Bulbapedia section title match, or (None, None).
    entry = bp_best(name, era, sections, own_set)
    if not entry:
        return None, None
    title, _, n, names_pack = entry
    if n is not None:
        return n * unit_multiplier(kind, name), "Bulbapedia"
    if kind == "Deck" and not names_pack:
        return 0, "Bulbapedia (no booster pack in contents)"
    return None, None


def num(s):
    return int(s) if s.isdigit() else WORDS.get(s.lower())


# The number of whole products in a listing of one product: "[Set of 3]", "(Set of 2)", "[Bundle of 2]", "Mini Tins 5-Pack",
# "8-Pack Mini Tins", "6-Pack Poke balls".
UNITS_RE = re.compile(r"[\[(](?:set|bundle) of (\d+)[\])]|\btins? (\d+)-pack\b|\b(\d+)-pack (?:mini tins|pok[eé] ?balls)\b", re.I)


def units_of(name):
    m = UNITS_RE.search(name)
    return int(next(g for g in m.groups() if g)) if m else 1


def unit_multiplier(kind, name):
    # A description or a Bulbapedia section gives the pack count for one unit. A booster pack listing, such as "Sleeved
    # Booster Pack Bundle [Set of 8]", already counts every pack.
    return 1 if kind == "Booster pack" else units_of(name)


def clean(text):
    return re.sub(r"\s+", " ", re.sub(r"<[^>]+>", " ", text or "")).strip()


def kind_of(name):
    low = name.lower()
    for kind, pat in KINDS:
        if re.search(pat, low):
            return kind
    return "Other"


def stadium_packs(hand_text):
    # "2 Build & Battle Boxes + 4 packs" or "2 Build & Battle Boxes plus 3 packs" in the set file's hand table.
    m = re.search(r"^\|\s*Build & Battle Stadium\s*\|\s*(\d+)\s+Build & Battle Box(?:es)?\s*(?:\+|plus)\s*(\d+)\s+packs?", hand_text or "", re.I | re.M)
    return int(m.group(1)) * DEFAULT_PACKS["Build & Battle"] + int(m.group(2)) if m else None


def packs_of(kind, name, text, era=None, sections=None, hand_text=None, own_set=frozenset()):
    if kind == "Case or display":
        return None, ""
    if re.search(r"\bstadium\b", name, re.I):
        # A stadium holds Build & Battle Boxes. The description and Bulbapedia count only its loose packs.
        n = stadium_packs(hand_text)
        return (n, "Set file") if n is not None else (None, "Unknown")
    # Add one count per distinct bullet: "• 4 Celebrations four-card booster packs • 2 additional Pokémon TCG booster
    # packs" is 6. The text before the first bullet often repeats a count, so it counts only with no bullet count.
    # A description of a multi-unit listing, such as "Crown Zenith Tin [Set of 3]", gives the count for one unit.
    bullets = list(dict.fromkeys(re.sub(r"\s+", " ", b).strip().lower() for b in text.split("•")[1:]))
    counts = [num(m.group(1)) for item in bullets for m in [PACKS_RE.search(item)] if m and num(m.group(1))]
    m = PACKS_RE.search(text)
    if counts or (m and num(m.group(1))):
        return (sum(counts) if counts else num(m.group(1))) * unit_multiplier(kind, name), "Description"
    # "N-Pack" is a pack count, but not in "POP Series 6 Pack", "Mini Tins 5-Pack", or "Collector 3-Pack: ... ETB + Tins".
    m = re.search(r"(?<!series )(?<!tins )(?<!tin )\b(\d+)[ -]pack\b(?!\s*:)(?! (?:mini tins|pok[eé] ?balls))", name, re.I)
    if m:
        return int(m.group(1)), "Name"
    m = re.search(r"\b(single|one|two|three|four|five|six)[ -](?:pack )?blister\b|\b(single|one|two|three|four|five|six)[ -]pack\b", name, re.I)
    if m:
        w = (m.group(1) or m.group(2)).lower()
        return (1 if w == "single" else WORDS[w]), "Name"
    m = re.search(r"\bset of (\d+)\b", name, re.I)
    if m and re.search(r"\bbooster pack\b", name, re.I):
        return int(m.group(1)), "Name"
    if re.search(r"\bsingle pack\b", name, re.I):
        return 1, "Name"
    if sections is not None:
        n, src = bp_packs(name, kind, era, sections, own_set)
        if src:
            return n, src
    if kind == "Build & Battle" and not re.search(r"\bbox\b", name, re.I):
        return None, "Unknown"
    if kind in DEFAULT_PACKS:
        return DEFAULT_PACKS[kind], "Kind default"
    return None, "Unknown"


def holds_of(name, text):
    for src in (text, name):
        m = HOLDS_RE.search(src)
        if m and num(m.group(1)):
            return f"{num(m.group(1))} {m.group(2).lower()}"
    m = re.search(r"\((\d+)\s*(?:ct|count)\)", name, re.I)
    if m:
        return f"{m.group(1)} units"
    m = re.search(r"(booster box|elite trainer box|booster bundle|build & battle box|mini tin|tin|blister|collection|booster pack|sleeved booster)[^()]*\b(?:case|display)\b", name, re.I)
    plural = {"booster box": "booster boxes", "elite trainer box": "elite trainer boxes", "build & battle box": "build & battle boxes"}
    return f"Unknown number of {plural.get(m.group(1).lower(), m.group(1).lower() + 's')}" if m else "Unknown"


def quarter(date):
    m = re.match(r"(\d{4})-(\d{2})", date or "")
    return f"{m.group(1)} Q{(int(m.group(2)) - 1) // 3 + 1}" if m else None


MONTHS = {m: i for i, m in enumerate("january february march april may june july august september october november december".split(), 1)}


def set_release_dates():
    out = {}
    for f in glob.glob(os.path.join(DOCS, "eras", "*.md")):
        for line in open(f):
            links = re.findall(r"\(\.\./([a-z0-9-]+)\.md\)", line)
            m = re.search(r"\b(January|February|March|April|May|June|July|August|September|October|November|December)\s+\d{1,2},\s+(\d{4})", line)
            iso = re.search(r"\b(\d{4})-(\d{2})-\d{2}\b", line)
            if links and m:
                out.setdefault(links[0], f"{m.group(2)}-{MONTHS[m.group(1).lower()]:02d}")
            elif links and iso:
                out.setdefault(links[0], f"{iso.group(1)}-{iso.group(2)}")
    for f in glob.glob(os.path.join(DOCS, "*.md")):
        slug = os.path.basename(f)[:-3]
        if slug in out:
            continue
        head = open(f).read()[:4000]
        m = re.search(r"(?i)english release[^\n]*?\b(January|February|March|April|May|June|July|August|September|October|November|December)\s+\d{1,2},\s+(\d{4})", head)
        iso = re.search(r"(?i)english release[^\n]*?\b(\d{4})-(\d{2})-\d{2}\b", head)
        if m:
            out[slug] = f"{m.group(2)}-{MONTHS[m.group(1).lower()]:02d}"
        elif iso:
            out[slug] = f"{iso.group(1)}-{iso.group(2)}"
    return out


def ppt_ids():
    ids = set()
    for f in glob.glob(os.path.join(SEALED, "[0-9]*.json")):
        ids.update(str(x.get("tcgPlayerId")) for x in json.load(open(f)).get("data", []))
    return ids


def products_by_group():
    groups = {g["groupId"]: g for g in json.load(open(os.path.join(SEALED, "_groups.json")))}
    out = collections.OrderedDict()
    for gid, g in groups.items():
        path = os.path.join(TCGCSV, f"{gid}-products.json")
        if not os.path.exists(path):
            continue
        rows = []
        for x in json.load(open(path))["results"]:
            ext = {e["name"]: e["value"] for e in x.get("extendedData", [])}
            text = clean(ext.get("CardText"))
            if "Number" in ext or "Rarity" in ext or x["name"].lower().startswith("code card") or "not a physical item" in text.lower():
                continue
            rows.append((x, text))
        out[gid] = (g, rows)
    return out


REMOVED = collections.Counter()


def build_rows(gid, rows, release_by_slug, priced, eras=None, sections=None):
    slug = SLUG_OF.get(gid)
    hand_text = ""
    if slug and os.path.exists(os.path.join(DOCS, f"{slug}.md")):
        doc = open(os.path.join(DOCS, f"{slug}.md")).read()
        m = re.search(r"^## Sealed products\n(.*?)(?=<!-- product-catalog:start|^## )", doc, re.S | re.M)
        hand_text = m.group(1) if m else ""
    out, own_set = [], own_set_tokens(gid)
    for x, text in sorted(rows, key=lambda r: (kind_of(r[0]["name"]), r[0]["name"])):
        kind = kind_of(x["name"])
        packs, src = packs_of(kind, x["name"], text, (eras or {}).get(slug), sections, hand_text, own_set)
        if is_deck_product(x["name"]) and (kind == "Case or display" or not packs):
            REMOVED[kind] += 1
            continue
        holds = holds_of(x["name"], text) if kind == "Case or display" else "—"
        rel = (x.get("presaleInfo") or {}).get("releasedOn")
        q = quarter(rel) or (quarter(release_by_slug.get(slug)) and f"{quarter(release_by_slug.get(slug))} (set)") or "—"
        out.append({"id": x["productId"], "name": x["name"].replace("|", "/"), "kind": kind,
                    "packs": str(packs) if packs is not None else ("—" if kind == "Case or display" else "Unknown"),
                    "src": src or "—", "holds": holds, "release": q, "ppt": "Yes" if str(x["productId"]) in priced else "No"})
    return out


def table(rows):
    lines = ["| TCGplayer ID | Product | Kind | Packs | Packs from | Pack mix | Mix confidence | Holds | Release | PPT price |",
             "|---|---|---|---|---|---|---|---|---|---|"]
    lines += [f"| {r['id']} | {r['name']} | {r['kind']} | {r['packs']} | {r['src']} | {r.get('mix', '—')} | {r.get('mix_confidence', '—')} "
              f"| {r['holds']} | {r['release']} | {r['ppt']} |" for r in rows]
    return "\n".join(lines)


def mix_text(mix, names):
    # "2 Battle Styles, 1 Darkness Ablaze, 1 unknown set", with the largest count first.
    def label(k):
        return "unknown set" if k == "unknown" else f"{k} (set unknown)" if k.endswith(" Series") else names.get(k, k)
    return ", ".join(f"{n} {label(k)}" for k, n in sorted(mix.items(), key=lambda kv: (-kv[1], label(kv[0])))) or "—"


def merge_contents(rows_lists):
    # Add the pack mix from tools/ppt/sealed_contents.py to each row. A researched count (tools/ppt/sealed_overrides.json)
    # or a raised count (packs_note) replaces the catalog count.
    import sealed_contents
    idx = open(os.path.join(ROOT, "docs", "13-sets.md")).read()
    names = {}
    for text, slug in re.findall(r"\[([^\]]+)\]\(sets/([a-z0-9-]+)\.md\)", idx):
        names.setdefault(slug, text)
    contents = {c["id"]: c for c in sealed_contents.all_contents()}
    for rows in rows_lists:
        for r in rows:
            c = contents.get(r["id"])
            if not c:
                continue
            if c["packs"] is not None and (c["source"] == "Research" or c["packs_note"]):
                r["packs"] = str(c["packs"])
                r["src"] = "Research" if c["source"] == "Research" else f"{r['src']} (raised)"
            r["mix"], r["mix_confidence"] = mix_text(c["mix"], names), c["confidence"]


INTRO = ("Every physical sealed product that the TCGplayer catalog (TCGCSV) lists for this set, fetched 2026-09-12. "
         "Code cards, and deck products with no booster pack (fixed cards, no random pull), are left out.\n\n"
         "- **Packs** is the number of booster packs. **Packs from** names the source: the TCGplayer description, "
         "the product name, the Bulbapedia TCG merchandise page for the series, the set file's own table (Build & Battle Stadium: boxes × 4 plus the extra packs), or a default for the kind (booster box 36, booster bundle 6, Build & Battle Box 4). "
         "Check a default before the game uses it. \"Research\" means a researched entry in `tools/ppt/sealed_overrides.json`, "
         "with its sources. \"(raised)\" means that Bulbapedia and the TCGplayer description show a higher count than the first read. "
         "For a listing of several units, such as \"[Set of 3]\" or \"Mini Tins 5-Pack\", Packs is the total for all units.\n"
         "- **Pack mix** is the number of packs from each set, from `tools/ppt/sealed_contents.py`. Mixes are typical, not guaranteed. "
         "\"unknown set\" means that no source names the set. \"<series> Series (set unknown)\" means that the source names only the series.\n"
         "- **Mix confidence**: Exact (every pack has a named set), Partial (some packs have no named set), Product set (a single-set "
         "product with no mix stated), Conflict (the sources disagree), or Unknown (no mix).\n"
         "- **Holds** is what a case or a display holds.\n"
         "- **Release** is the quarter from the TCGplayer release date. \"(set)\" means the quarter of the set's release date.\n"
         "- **PPT price** is Yes when PokemonPriceTracker has a price. Prices are in `tools/ppt/cache/sealed/`, not in the docs.\n")


def write_set(slug, rows, groups_used):
    path = os.path.join(DOCS, f"{slug}.md")
    t = open(path).read()
    block = f"{MARK_START}\n### Product catalog\n\n{INTRO}\nTCGplayer group {', '.join(f'`{g}`' for g in groups_used)}: {len(rows)} products.\n\n{table(rows)}\n{MARK_END}\n"
    if MARK_START in t:
        t = t[:t.index(MARK_START)] + block + t[t.index(MARK_END) + len(MARK_END) + 1:]
    else:
        m = re.search(r"^## Sealed products\n.*?(?=^## )", t, re.S | re.M)
        if not m:
            raise SystemExit(f"{slug}: no '## Sealed products' section")
        t = t[:m.end()] + block + "\n" + t[m.end():]
    open(path, "w").write(t)


if __name__ == "__main__":
    write = "--write" in sys.argv
    release_by_slug, priced = set_release_dates(), ppt_ids()
    idx = open(os.path.join(ROOT, "docs", "13-sets.md")).read()
    eras = {}
    for mm in re.finditer(r"^- \*\*(.+?)\*\* —\s*\n?\s*\[eras/([^\]]+)\.md\].*?(?=^- \*\*|\Z)", idx, re.S | re.M):
        for s in re.findall(r"\(sets/([a-z0-9-]+)\.md\)", mm.group(0)):
            eras.setdefault(s, mm.group(2))
    sections = bp_sections()
    by_group = products_by_group()
    stats = collections.defaultdict(collections.Counter)
    per_slug = collections.defaultdict(list); groups_of_slug = collections.defaultdict(list); multi = []
    for gid, (g, rows) in by_group.items():
        built = build_rows(gid, rows, release_by_slug, priced, eras, sections)
        for r in built:
            stats[r["kind"]]["total"] += 1
            stats[r["kind"]][r["src"]] += 1
            stats["_all"]["release known"] += r["release"] != "—"
            stats["_all"]["ppt priced"] += r["ppt"] == "Yes"
            stats["_all"]["total"] += 1
        if gid in SLUG_OF:
            per_slug[SLUG_OF[gid]] += built
            groups_of_slug[SLUG_OF[gid]].append(gid)
        elif built:
            multi.append((g, built))
    for kind, c in sorted(stats.items()):
        print(f"{kind}: {dict(c)}")
    print(f"sets with products: {len(per_slug)}; multi-set groups with products: {len(multi)}")
    print(f"deck products left out, by kind: {dict(REMOVED)}")
    sample = per_slug.get("black-bolt", [])[:8]
    print(table(sample))
    if write:
        merge_contents(list(per_slug.values()) + [rows for _, rows in multi])
        for slug, rows in per_slug.items():
            write_set(slug, rows, groups_of_slug[slug])
        lines = ["# Sealed products outside the set files", "",
                 "Sealed products in TCGplayer groups that have no set file: multi-set products, trainer kits, "
                 "Battle Academy, promotional groups, and sets that are newer than the set files.", "",
                 "Generated by `python3 tools/ppt/sealed_catalog.py --write`. Do not edit by hand.", "", INTRO]
        for g, rows in sorted(multi, key=lambda gr: gr[0]["name"]):
            lines += [f"## {g['name']}", "", f"TCGplayer group `{g['groupId']}`: {len(rows)} products.", "", table(rows), ""]
        open(os.path.join(DOCS, "sealed-multi-set.md"), "w").write("\n".join(lines))
        print("wrote", len(per_slug), "set files and sealed-multi-set.md")
