"""Write a generated sealed product catalog into the set files, from the TCGCSV catalog and the PPT sealed cache.

Usage:
  python3 tools/ppt/sealed_catalog.py            dry run: report the parse rates and sample rows
  python3 tools/ppt/sealed_catalog.py --write    write '### Product catalog' in each set file, and
                                                  docs/sets/sealed-multi-set.md for the other groups

For each physical sealed product (TCGCSV products with no card number; code cards are left out):
- Kind: from whole words in the product name.
- Packs: from the TCGplayer description, then the product name, then a default for the kind.
  The 'Packs from' column names the source. Other products get 'Unknown'.
- Holds: for a case or a display, what it holds (from the description or the name).
- Release: the TCGCSV release date, else the set's release date from its era file or set file (quarter).
- PPT price: yes when the PPT sealed cache has the product.
Prices change daily, so they stay in tools/ppt/cache/. The docs hold only facts that do not change.
"""
import collections, glob, json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..", "..")
DOCS = os.path.join(ROOT, "docs", "sets")
TCGCSV = os.path.join(ROOT, "tools", "cardlist", "cache", "tcgcsv")
SEALED = os.path.join(HERE, "cache", "sealed")
GROUP_MAP = json.load(open(os.path.join(ROOT, "tools", "cardlist", "tcgcsv-map.json")))
SLUG_OF = {g: s for s, gs in GROUP_MAP.items() for g in gs}
MARK_START = "<!-- product-catalog:start (generated by tools/ppt/sealed_catalog.py; do not edit) -->"
MARK_END = "<!-- product-catalog:end -->"

WORDS = {w: i for i, w in enumerate("zero one two three four five six seven eight nine ten eleven twelve".split())}
WORDS.update({"eighteen": 18, "twenty": 20, "twenty-four": 24, "thirty-six": 36, "thirty six": 36, "forty": 40})
NUM = r"(\d+|" + "|".join(sorted(map(re.escape, WORDS), key=len, reverse=True)) + r")"
PACKS_RE = re.compile(NUM + r"\s+(?:\(\d+\)\s+)?(?:[\w&.:'’—–-]+\s+){0,8}?(?:booster|mini)\s+packs?\b", re.I)
HOLDS_RE = re.compile(NUM + r"\s+(?:[\w&.:'’—–-]+\s+){0,6}?(booster boxes|elite trainer boxes|booster bundles|build & battle boxes|"
                      r"collections|tins|blisters|trainer kits|theme decks|mini tins)\b", re.I)
KINDS = [
    ("Case or display", r"\b(case|display)\b"),
    ("Booster box", r"\bbooster box\b"),
    ("Elite Trainer Box", r"\belite trainer box\b"),
    ("Deck", r"\b(theme deck|starter deck|battle deck|trainer kit|training kit|league battle|world championship|deck bundle)\b"),
    ("Booster pack", r"\bmini booster pack\b|\bbooster pack$"),
    ("Booster bundle", r"\bbooster bundle\b"),
    ("Build & Battle", r"\bbuild (?:&|and) battle\b"),
    ("Blister", r"\bblisters?\b|\bcheck ?lane\b"),
    ("Tin", r"\btins?\b"),
    ("Booster pack", r"\b(booster pack|sleeved booster|fun pack|mini booster)\b"),
    ("Collection", r"\b(collection|premium|box|chest|binder|album|figure|poster|pin)\b"),
]
DEFAULT_PACKS = {"Booster box": 36, "Booster bundle": 6, "Build & Battle": 4, "Booster pack": 1}
BULBAPEDIA = os.path.join(HERE, "cache", "bulbapedia")
BP_PAGES = {"wizards-of-the-coast": ["Original", "Neo"], "e-card": ["Legendary Collection", "E-Card"], "ex": ["EX"],
            "diamond-pearl-platinum": ["Diamond & Pearl", "Platinum"],
            "heartgold-soulsilver": ["HeartGold & SoulSilver", "Call of Legends"], "black-white": ["Black & White"],
            "xy": ["XY"], "sun-moon": ["Sun & Moon"], "sword-shield": ["Sword & Shield"],
            "scarlet-violet": ["Scarlet & Violet"], "mega-evolution": ["Mega Evolution"]}
BP_STOP = {"pokemon", "tcg", "the", "and", "of", "series", "xy", "sm", "sun", "moon", "sword", "shield", "scarlet",
           "violet", "mega", "evolution", "black", "white", "ex", "gx", "v"}
BP_KEY = ("tin", "box", "collection", "deck", "blister", "elite", "trainer", "kit", "pack", "bundle", "chest", "binder",
          "album", "arena", "stadium")


def bp_clean(s):
    s = re.sub(r"\{\{TCGMerchGallery.*?\n\}\}", " ", s, flags=re.S)
    s = re.sub(r"\{\{(?:TCG|p|TCGMerch)\|(?:[^{}|]*\|)*([^{}|]*)\}\}", r"\1", s)
    s = re.sub(r"\[\[(?:[^\]|]*\|)?([^\]]*)\]\]", r"\1", s)
    s = re.sub(r"\{\{[^{}]*\}\}", " ", s)
    s = re.sub(r"'{2,3}|<[^>]+>", "", s)
    return re.sub(r"\s+", " ", s)


def bp_tokens(name):
    name = re.sub(r"\[.*?\]|\(.*?\)", " ", name.lower()).replace("-", " ").replace("é", "e")
    return {re.sub(r"(es|s)$", "", w) if len(w) > 3 else w for w in re.findall(r"[a-z0-9]+", name)} - BP_STOP


def bp_sections():
    # {page name: [(section title, title tokens, pack count or None, the text names a booster pack)]}
    import subprocess, urllib.parse
    os.makedirs(BULBAPEDIA, exist_ok=True)
    out = {}
    for page in sorted({p for v in BP_PAGES.values() for p in v}):
        title = f"{page} TCG Series merchandise"
        path = os.path.join(BULBAPEDIA, title.replace(" ", "_").replace("&", "_") + ".wiki")
        if not os.path.exists(path) or os.path.getsize(path) < 500:
            subprocess.run(["curl", "-sL", "-m", "60", "-A", "PokeVendor-research/1.0", "-o", path,
                            "https://bulbapedia.bulbagarden.net/w/index.php?title=" + urllib.parse.quote(title) + "&action=raw"])
        parts = re.split(r"^==([^=].*?)==\s*$", open(path, errors="ignore").read(), flags=re.M)
        secs = []
        for i in range(1, len(parts) - 1, 2):
            text = bp_clean(parts[i + 1]).split("Product images:")[0]
            m = PACKS_RE.search(text)
            n = num(m.group(1)) if m else None
            if n is None and re.search(r"\b(?:a|one)\s+(?:[\w&'’.:-]+\s+){0,3}?booster pack\b", text, re.I):
                n = 1
            secs.append((parts[i].strip(), bp_tokens(parts[i]), n, bool(re.search(r"booster pack", text, re.I))))
        out[page] = secs
    return out


def bp_packs(name, kind, era, sections):
    # (packs, source) from the best Bulbapedia section title match, or (None, None).
    nt = bp_tokens(name)
    best = (0.0, None)
    for page in BP_PAGES.get(era) or [p for v in BP_PAGES.values() for p in v]:
        for title, tt, n, names_pack in sections.get(page, []):
            if not tt or not (nt & tt):
                continue
            if not any(k in " ".join(nt) and k in " ".join(tt) for k in BP_KEY):
                continue
            score = len(nt & tt) / len(nt | tt)
            if score > best[0]:
                best = (score, (title, n, names_pack))
    if not best[1] or best[0] < 0.6:
        return None, None
    title, n, names_pack = best[1]
    mult = re.search(r"\[(?:bundle|set) of (\d+)\]", name, re.I)
    if n is not None:
        return n * (int(mult.group(1)) if mult else 1), "Bulbapedia"
    if kind == "Deck" and not names_pack:
        return 0, "Bulbapedia (no booster pack in contents)"
    return None, None


def num(s):
    return int(s) if s.isdigit() else WORDS.get(s.lower())


def clean(text):
    return re.sub(r"\s+", " ", re.sub(r"<[^>]+>", " ", text or "")).strip()


def kind_of(name):
    low = name.lower()
    for kind, pat in KINDS:
        if re.search(pat, low):
            return kind
    return "Other"


def packs_of(kind, name, text, era=None, sections=None):
    if kind == "Case or display":
        return None, ""
    m = PACKS_RE.search(text)
    if m and num(m.group(1)):
        return num(m.group(1)), "Description"
    m = re.search(r"\b(\d+)[ -]pack\b", name, re.I)
    if m:
        return int(m.group(1)), "Name"
    m = re.search(r"\b(single|one|two|three|four|five|six)[ -](?:pack )?blister\b|\b(single|one|two|three|four|five|six)[ -]pack\b", name, re.I)
    if m:
        w = (m.group(1) or m.group(2)).lower()
        return (1 if w == "single" else WORDS[w]), "Name"
    m = re.search(r"\bset of (\d+)\b", name, re.I)
    if m and re.search(r"\bbooster pack\b", name, re.I):
        return int(m.group(1)), "Name"
    if re.search(r"\bsingle pack\b", name, re.I):
        return 1, "Name"
    if sections is not None and not re.search(r"\bstadium\b", name, re.I):
        # A stadium holds other boxed products; the first pack phrase counts only its loose packs.
        n, src = bp_packs(name, kind, era, sections)
        if src:
            return n, src
    if kind == "Build & Battle" and not re.search(r"\bbox\b", name, re.I):
        return None, "Unknown"
    if kind in DEFAULT_PACKS:
        return DEFAULT_PACKS[kind], "Kind default"
    return None, "Unknown"


def holds_of(name, text):
    for src in (text, name):
        m = HOLDS_RE.search(src)
        if m and num(m.group(1)):
            return f"{num(m.group(1))} {m.group(2).lower()}"
    m = re.search(r"\((\d+)\s*(?:ct|count)\)", name, re.I)
    if m:
        return f"{m.group(1)} units"
    m = re.search(r"(booster box|elite trainer box|booster bundle|build & battle box|mini tin|tin|blister|collection|booster pack|sleeved booster)[^()]*\b(?:case|display)\b", name, re.I)
    plural = {"booster box": "booster boxes", "elite trainer box": "elite trainer boxes", "build & battle box": "build & battle boxes"}
    return f"Unknown number of {plural.get(m.group(1).lower(), m.group(1).lower() + 's')}" if m else "Unknown"


def quarter(date):
    m = re.match(r"(\d{4})-(\d{2})", date or "")
    return f"{m.group(1)} Q{(int(m.group(2)) - 1) // 3 + 1}" if m else None


MONTHS = {m: i for i, m in enumerate("january february march april may june july august september october november december".split(), 1)}


def set_release_dates():
    out = {}
    for f in glob.glob(os.path.join(DOCS, "eras", "*.md")):
        for line in open(f):
            links = re.findall(r"\(\.\./([a-z0-9-]+)\.md\)", line)
            m = re.search(r"\b(January|February|March|April|May|June|July|August|September|October|November|December)\s+\d{1,2},\s+(\d{4})", line)
            iso = re.search(r"\b(\d{4})-(\d{2})-\d{2}\b", line)
            if links and m:
                out.setdefault(links[0], f"{m.group(2)}-{MONTHS[m.group(1).lower()]:02d}")
            elif links and iso:
                out.setdefault(links[0], f"{iso.group(1)}-{iso.group(2)}")
    for f in glob.glob(os.path.join(DOCS, "*.md")):
        slug = os.path.basename(f)[:-3]
        if slug in out:
            continue
        head = open(f).read()[:4000]
        m = re.search(r"(?i)english release[^\n]*?\b(January|February|March|April|May|June|July|August|September|October|November|December)\s+\d{1,2},\s+(\d{4})", head)
        iso = re.search(r"(?i)english release[^\n]*?\b(\d{4})-(\d{2})-\d{2}\b", head)
        if m:
            out[slug] = f"{m.group(2)}-{MONTHS[m.group(1).lower()]:02d}"
        elif iso:
            out[slug] = f"{iso.group(1)}-{iso.group(2)}"
    return out


def ppt_ids():
    ids = set()
    for f in glob.glob(os.path.join(SEALED, "[0-9]*.json")):
        ids.update(str(x.get("tcgPlayerId")) for x in json.load(open(f)).get("data", []))
    return ids


def products_by_group():
    groups = {g["groupId"]: g for g in json.load(open(os.path.join(SEALED, "_groups.json")))}
    out = collections.OrderedDict()
    for gid, g in groups.items():
        path = os.path.join(TCGCSV, f"{gid}-products.json")
        if not os.path.exists(path):
            continue
        rows = []
        for x in json.load(open(path))["results"]:
            ext = {e["name"]: e["value"] for e in x.get("extendedData", [])}
            text = clean(ext.get("CardText"))
            if "Number" in ext or "Rarity" in ext or x["name"].lower().startswith("code card") or "not a physical item" in text.lower():
                continue
            rows.append((x, text))
        out[gid] = (g, rows)
    return out


def build_rows(gid, rows, release_by_slug, priced, eras=None, sections=None):
    slug = SLUG_OF.get(gid)
    out = []
    for x, text in sorted(rows, key=lambda r: (kind_of(r[0]["name"]), r[0]["name"])):
        kind = kind_of(x["name"])
        packs, src = packs_of(kind, x["name"], text, (eras or {}).get(slug), sections)
        holds = holds_of(x["name"], text) if kind == "Case or display" else "—"
        rel = (x.get("presaleInfo") or {}).get("releasedOn")
        q = quarter(rel) or (quarter(release_by_slug.get(slug)) and f"{quarter(release_by_slug.get(slug))} (set)") or "—"
        out.append({"id": x["productId"], "name": x["name"].replace("|", "/"), "kind": kind,
                    "packs": str(packs) if packs is not None else ("—" if kind == "Case or display" else "Unknown"),
                    "src": src or "—", "holds": holds, "release": q, "ppt": "Yes" if str(x["productId"]) in priced else "No"})
    return out


def table(rows):
    lines = ["| TCGplayer ID | Product | Kind | Packs | Packs from | Holds | Release | PPT price |", "|---|---|---|---|---|---|---|---|"]
    lines += [f"| {r['id']} | {r['name']} | {r['kind']} | {r['packs']} | {r['src']} | {r['holds']} | {r['release']} | {r['ppt']} |" for r in rows]
    return "\n".join(lines)


INTRO = ("Every physical sealed product that the TCGplayer catalog (TCGCSV) lists for this set, fetched 2026-09-12. "
         "Code cards are left out.\n\n"
         "- **Packs** is the number of booster packs. **Packs from** names the source: the TCGplayer description, "
         "the product name, the Bulbapedia TCG merchandise page for the series, or a default for the kind (booster box 36, booster bundle 6, Build & Battle Box 4). "
         "Check a default before the game uses it.\n"
         "- **Holds** is what a case or a display holds.\n"
         "- **Release** is the quarter from the TCGplayer release date. \"(set)\" means the quarter of the set's release date.\n"
         "- **PPT price** is Yes when PokemonPriceTracker has a price. Prices are in `tools/ppt/cache/sealed/`, not in the docs.\n")


def write_set(slug, rows, groups_used):
    path = os.path.join(DOCS, f"{slug}.md")
    t = open(path).read()
    block = f"{MARK_START}\n### Product catalog\n\n{INTRO}\nTCGplayer group {', '.join(f'`{g}`' for g in groups_used)}: {len(rows)} products.\n\n{table(rows)}\n{MARK_END}\n"
    if MARK_START in t:
        t = t[:t.index(MARK_START)] + block + t[t.index(MARK_END) + len(MARK_END) + 1:]
    else:
        m = re.search(r"^## Sealed products\n.*?(?=^## )", t, re.S | re.M)
        if not m:
            raise SystemExit(f"{slug}: no '## Sealed products' section")
        t = t[:m.end()] + block + "\n" + t[m.end():]
    open(path, "w").write(t)


if __name__ == "__main__":
    write = "--write" in sys.argv
    release_by_slug, priced = set_release_dates(), ppt_ids()
    idx = open(os.path.join(ROOT, "docs", "13-sets.md")).read()
    eras = {}
    for mm in re.finditer(r"^- \*\*(.+?)\*\* —\s*\n?\s*\[eras/([^\]]+)\.md\].*?(?=^- \*\*|\Z)", idx, re.S | re.M):
        for s in re.findall(r"\(sets/([a-z0-9-]+)\.md\)", mm.group(0)):
            eras.setdefault(s, mm.group(2))
    sections = bp_sections()
    by_group = products_by_group()
    stats = collections.defaultdict(collections.Counter)
    per_slug = collections.defaultdict(list); groups_of_slug = collections.defaultdict(list); multi = []
    for gid, (g, rows) in by_group.items():
        built = build_rows(gid, rows, release_by_slug, priced, eras, sections)
        for r in built:
            stats[r["kind"]]["total"] += 1
            stats[r["kind"]][r["src"]] += 1
            stats["_all"]["release known"] += r["release"] != "—"
            stats["_all"]["ppt priced"] += r["ppt"] == "Yes"
            stats["_all"]["total"] += 1
        if gid in SLUG_OF:
            per_slug[SLUG_OF[gid]] += built
            groups_of_slug[SLUG_OF[gid]].append(gid)
        elif built:
            multi.append((g, built))
    for kind, c in sorted(stats.items()):
        print(f"{kind}: {dict(c)}")
    print(f"sets with products: {len(per_slug)}; multi-set groups with products: {len(multi)}")
    sample = per_slug.get("black-bolt", [])[:8]
    print(table(sample))
    if write:
        for slug, rows in per_slug.items():
            write_set(slug, rows, groups_of_slug[slug])
        lines = ["# Sealed products outside the set files", "",
                 "Sealed products in TCGplayer groups that have no set file: multi-set products, trainer kits, "
                 "Battle Academy, promotional groups, and sets that are newer than the set files.", "",
                 "Generated by `python3 tools/ppt/sealed_catalog.py --write`. Do not edit by hand.", "", INTRO]
        for g, rows in sorted(multi, key=lambda gr: gr[0]["name"]):
            lines += [f"## {g['name']}", "", f"TCGplayer group `{g['groupId']}`: {len(rows)} products.", "", table(rows), ""]
        open(os.path.join(DOCS, "sealed-multi-set.md"), "w").write("\n".join(lines))
        print("wrote", len(per_slug), "set files and sealed-multi-set.md")
